name: jstmc
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - numpy=1.23.5
  - matplotlib=3.6.2
  - scipy=0.1.23
  - simple-parsing
  - sigpy=0.1.23
  - tqdm=4.64.1
  - numba=0.56.4
  - pathtools
  - pip
  - pip:
      - -e git+https://github.com/schmidtijoe/pypulseq@dev
