name: jstmc
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - pandas=1.4.3
  - matplotlib=3.6.1
  - simple-parsing=0.0.20
  - numpy=1.22.3
  - python=3.8
  - pathtools=0.1.2
  - pip
  - pip:
      - git+https://github.com/imr-framework/pypulseq@dev